services:
  weatherflow-collector-08ce4425:
    container_name: weatherflow-collector-08ce4425
    environment:
      TZ: America/Chicago
      WEATHERFLOW_COLLECTOR_DEBUG: "false"
      WEATHERFLOW_COLLECTOR_DEBUG_CURL: "false"
      WEATHERFLOW_COLLECTOR_DISABLE_HEALTH_CHECK: "false"
      WEATHERFLOW_COLLECTOR_DISABLE_HOST_PERFORMANCE: "false"
      WEATHERFLOW_COLLECTOR_DISABLE_LOCAL_UDP: "false"
      WEATHERFLOW_COLLECTOR_DISABLE_REMOTE_FORECAST: "false"
      WEATHERFLOW_COLLECTOR_DISABLE_REMOTE_REST: "false"
      WEATHERFLOW_COLLECTOR_DISABLE_REMOTE_SOCKET: "false"
      WEATHERFLOW_COLLECTOR_HEALTHCHECK: "true"
      WEATHERFLOW_COLLECTOR_HOST_HOSTNAME: Justins-iMac.local
      WEATHERFLOW_COLLECTOR_INFLUXDB_PASSWORD: x8egQTrf4bGl8Cs3XGyF1yE0b06pfgJe
      WEATHERFLOW_COLLECTOR_INFLUXDB_URL: http://influxdb:8086/write?db=weatherflow
      WEATHERFLOW_COLLECTOR_INFLUXDB_USERNAME: weatherflow
      WEATHERFLOW_COLLECTOR_THREADS: 4
      WEATHERFLOW_COLLECTOR_TOKEN: 08ce4425-e579-497b-a6b0-7a47043bc548
    image: lux4rd0/weatherflow-collector:latest
    ports:
    - protocol: udp
      published: 50222
      target: 50222
    restart: always
version: '3.3'
